language: python

matrix:
  include:
    - python: 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs npm

install:
  - pip install coveralls
  # install python dependencies
  - pip install -r requirements.txt --upgrade --target lib/
  # install node dependencies
  - npm install

script:
  # npm (setup + build + test + compile + copy), should run first to set up static directory
  - npm run publish
  # python, we run lint with coverage and display coverage output
  - bin/pylint --python=python
  - bin/coverage --python=python

after_success:
  coveralls
