language: python

matrix:
  include:
    - python: 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs npm

install:
  # install python dependencies
  - pip install -r requirements.txt --upgrade --target lib/
  # setup node dependencies
  - npm run setup

script:
  # python, we run lint with coverage
  - python run_pylint.py src test *.py
  - python run_coverage.py run --source=src setup.py test
  # display report in logs
  - python run_coverage.py report
  # npm (setup + build + test + compile)
  - npm run publish

after_success:
  coveralls
